import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb/connection';
import { User } from '@/models/User';
import { Category } from '@/models/Category';
import { Listing } from '@/models/Listing';
import { Review } from '@/models/Review';

async function seed() {
  await connectToDatabase();

  const userCount = await User.countDocuments();
  if (userCount === 0) {
    await User.create([
      {
        id: 'user-001',
        name: 'Tech Solutions Store',
        email: 'tech@example.com',
        image: 'https://images.unsplash.com/photo-1560179707-f14e90b0c7c4?w=200',
        role: 'seller',
        bio: 'We provide premium tech products and digital services',
        location: 'New York, USA',
        website: 'https://techsolutions.example.com',
      },
      {
        id: 'user-002',
        name: 'Creative Design Hub',
        email: 'design@example.com',
        image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200',
        role: 'seller',
        bio: 'Professional graphic design and branding services',
        location: 'London, UK',
        website: 'https://creativedesignhub.example.com',
      },
      {
        id: 'user-003',
        name: 'Digital Marketing Pro',
        email: 'marketing@example.com',
        image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=200',
        role: 'seller',
        bio: 'SEO, social media marketing, and advertising expert',
        location: 'San Francisco, USA',
        website: 'https://digitalmarketingpro.example.com',
      },
      {
        id: 'user-004',
        name: 'Code Masters',
        email: 'code@example.com',
        image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200',
        role: 'seller',
        bio: 'Full-stack development and software solutions',
        location: 'Berlin, Germany',
        website: 'https://codemasters.example.com',
      },
      {
        id: 'user-005',
        name: 'Media Studio',
        email: 'media@example.com',
        image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
        role: 'seller',
        bio: 'Video production, animation, and editing services',
        location: 'Los Angeles, USA',
        website: 'https://mediastudio.example.com',
      },
      {
        id: 'user-006',
        name: 'Pixel Perfect Graphics',
        email: 'pixel@example.com',
        image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=200',
        role: 'seller',
        bio: 'UI/UX design, illustrations, and brand identity',
        location: 'Toronto, Canada',
        website: 'https://pixelperfect.example.com',
      },
      {
        id: 'user-007',
        name: 'Cloud Hosting Services',
        email: 'cloud@example.com',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=200',
        role: 'seller',
        bio: 'Reliable cloud hosting, domains, and server management',
        location: 'Singapore',
        website: 'https://cloudhosting.example.com',
      },
      {
        id: 'user-008',
        name: 'WriteWell Agency',
        email: 'write@example.com',
        image: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=200',
        role: 'seller',
        bio: 'Content writing, copywriting, and translation in 12 languages',
        location: 'Dublin, Ireland',
        website: 'https://writewell.example.com',
      },
      {
        id: 'user-009',
        name: 'GameZone Accounts',
        email: 'games@example.com',
        image: 'https://images.unsplash.com/photo-1511512578045-d9209520d8b4?w=200',
        role: 'seller',
        bio: 'Premium gaming accounts, in-game items, and boosting services',
        location: 'Tokyo, Japan',
        website: 'https://gamezone.example.com',
      },
      {
        id: 'user-010',
        name: 'Mobile Gadgets Hub',
        email: 'gadgets@example.com',
        image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=200',
        role: 'seller',
        bio: 'Latest smartphones, accessories, and wearable tech',
        location: 'Dubai, UAE',
        website: 'https://mobilegadgets.example.com',
      },
      {
        id: 'user-011',
        name: 'SoundWave Studio',
        email: 'audio@example.com',
        image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200',
        role: 'seller',
        bio: 'Music production, mixing, mastering, and sound effects',
        location: 'Nashville, USA',
        website: 'https://soundwave.example.com',
      },
      {
        id: 'user-012',
        name: 'PhotoPro Gallery',
        email: 'photo@example.com',
        image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=200',
        role: 'seller',
        bio: 'Stock photography, photo editing, and drone footage',
        location: 'Auckland, New Zealand',
        website: 'https://photopro.example.com',
      },
      {
        id: 'user-013',
        name: 'Account Marketplace',
        email: 'accounts@example.com',
        image: 'https://images.unsplash.com/photo-1563986768609-322da13575f2?w=200',
        role: 'seller',
        bio: 'Social media, streaming, and business account sales',
        location: 'Mumbai, India',
        website: 'https://accountmarket.example.com',
      },
      {
        id: 'user-014',
        name: 'Software License Store',
        email: 'licenses@example.com',
        image: 'https://images.unsplash.com/photo-1555066931-436663dc9c2a?w=200',
        role: 'seller',
        bio: 'Genuine software licenses, tools, and enterprise solutions',
        location: 'Amsterdam, Netherlands',
        website: 'https://softwarelicenses.example.com',
      },
      {
        id: 'user-015',
        name: 'SEO Growth Partners',
        email: 'seo@example.com',
        image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=200',
        role: 'seller',
        bio: 'SEO audits, link building, and organic growth strategies',
        location: 'Chicago, USA',
        website: 'https://seogrowth.example.com',
      },
    ]);
  }

  const categoryCount = await Category.countDocuments();
  if (categoryCount === 0) {
    await Category.insertMany([
      { name: 'Web Development', slug: 'web-development', description: 'Professional web development services', icon: '💻' },
      { name: 'Graphic Design', slug: 'graphic-design', description: 'Logo design, branding, and visual identity', icon: '🎨' },
      { name: 'Digital Marketing', slug: 'digital-marketing', description: 'SEO, social media, and advertising', icon: '📈' },
      { name: 'Writing & Translation', slug: 'writing-translation', description: 'Content writing and translation services', icon: '✍️' },
      { name: 'Video & Animation', slug: 'video-animation', description: 'Video editing, animation, and production', icon: '🎬' },
      { name: 'Music & Audio', slug: 'music-audio', description: 'Music production, mixing, and mastering', icon: '🎵' },
      { name: 'Accounts', slug: 'accounts', description: 'Buy and sell social media, gaming, and business accounts', icon: '👤' },
      { name: 'Electronics', slug: 'electronics', description: 'Gadgets, phones, laptops, and accessories', icon: '📱' },
      { name: 'Software', slug: 'software', description: 'Software licenses, tools, and applications', icon: '📦' },
      { name: 'Photography', slug: 'photography', description: 'Photography services and stock photos', icon: '📷' },
    ]);
  }

  const categories = await Category.find().lean();
  const categoryMap = new Map(categories.map(c => [c.slug, c._id]));

  const listingCount = await Listing.countDocuments();
  if (listingCount === 0) {
    const listings = [
      {
        sellerId: 'user-001',
        title: 'Custom Website Development',
        description: 'Professional responsive website built with React, Next.js, and Node.js. Includes database integration, payment setup, and deployment.',
        price: 1500.00,
        discountPrice: 1299.00,
        discountPercentage: 13,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800'],
        tags: ['web', 'react', 'nextjs', 'nodejs'],
        deliveryTime: 21,
        revisions: 5,
        views: 450,
        sales: 38,
        rating: 4.9,
        reviewCount: 42,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-001',
        title: 'E-commerce Website Package',
        description: 'Complete e-commerce solution with Stripe integration, inventory management, and admin dashboard.',
        price: 2500.00,
        discountPrice: 1999.00,
        discountPercentage: 20,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800'],
        tags: ['ecommerce', 'shopify', 'stripe'],
        deliveryTime: 30,
        revisions: 8,
        views: 320,
        sales: 25,
        rating: 4.8,
        reviewCount: 31,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-001',
        title: 'Windows 11 Pro License',
        description: 'Genuine Windows 11 Pro license key with lifetime validity. Instant delivery via email.',
        price: 89.99,
        discountPrice: 69.99,
        discountPercentage: 22,
        categoryId: categoryMap.get('software')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800'],
        tags: ['windows', 'license', 'software'],
        deliveryTime: 1,
        revisions: 0,
        views: 890,
        sales: 156,
        rating: 4.7,
        reviewCount: 89,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-002',
        title: 'Professional Logo Design',
        description: 'Modern and memorable logo design with unlimited revisions. Includes vector files and brand guidelines.',
        price: 199.00,
        discountPrice: 149.00,
        discountPercentage: 25,
        categoryId: categoryMap.get('graphic-design')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1626785774573-4b799314346d?w=800'],
        tags: ['logo', 'branding', 'design'],
        deliveryTime: 5,
        revisions: 10,
        views: 680,
        sales: 124,
        rating: 4.9,
        reviewCount: 98,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-002',
        title: 'Social Media Branding Package',
        description: 'Complete branding package including logo, color palette, typography, and social media templates.',
        price: 499.00,
        discountPrice: 399.00,
        discountPercentage: 20,
        categoryId: categoryMap.get('graphic-design')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800'],
        tags: ['branding', 'social-media', 'templates'],
        deliveryTime: 7,
        revisions: 5,
        views: 420,
        sales: 67,
        rating: 4.8,
        reviewCount: 54,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-002',
        title: 'Premium Icon Set - 500+ Icons',
        description: 'High-quality vector icons for web and mobile apps. SVG, PNG, and Figma formats included.',
        price: 49.00,
        discountPrice: 29.00,
        discountPercentage: 41,
        categoryId: categoryMap.get('graphic-design')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800'],
        tags: ['icons', 'vector', 'ui'],
        deliveryTime: 1,
        revisions: 0,
        views: 230,
        sales: 89,
        rating: 4.6,
        reviewCount: 45,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-003',
        title: 'SEO Optimization Package',
        description: 'Complete SEO audit and optimization for your website. Includes keyword research, on-page SEO, and technical improvements.',
        price: 599.00,
        discountPrice: 499.00,
        discountPercentage: 17,
        categoryId: categoryMap.get('digital-marketing')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800'],
        tags: ['seo', 'optimization', 'marketing'],
        deliveryTime: 14,
        revisions: 3,
        views: 560,
        sales: 78,
        rating: 4.7,
        reviewCount: 65,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-003',
        title: 'Social Media Management (1 Month)',
        description: 'Full social media management for 3 platforms. Includes content creation, scheduling, and analytics reports.',
        price: 799.00,
        discountPrice: 699.00,
        discountPercentage: 13,
        categoryId: categoryMap.get('digital-marketing')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800'],
        tags: ['social-media', 'management', 'content'],
        deliveryTime: 30,
        revisions: 5,
        views: 340,
        sales: 45,
        rating: 4.6,
        reviewCount: 38,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-004',
        title: 'React Native Mobile App',
        description: 'Cross-platform mobile app development for iOS and Android. Includes push notifications and backend integration.',
        price: 3500.00,
        discountPrice: 2999.00,
        discountPercentage: 14,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800'],
        tags: ['react-native', 'mobile', 'ios', 'android'],
        deliveryTime: 45,
        revisions: 10,
        views: 280,
        sales: 19,
        rating: 4.9,
        reviewCount: 22,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-004',
        title: 'API Development & Integration',
        description: 'Custom REST API development with authentication, documentation, and third-party integrations.',
        price: 1200.00,
        discountPrice: 999.00,
        discountPercentage: 17,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800'],
        tags: ['api', 'backend', 'integration'],
        deliveryTime: 14,
        revisions: 5,
        views: 190,
        sales: 34,
        rating: 4.8,
        reviewCount: 28,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-005',
        title: 'Professional Video Editing',
        description: 'High-quality video editing for YouTube, social media, or business. Includes color grading, sound design, and motion graphics.',
        price: 299.00,
        discountPrice: 249.00,
        discountPercentage: 17,
        categoryId: categoryMap.get('video-animation')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800'],
        tags: ['video', 'editing', 'youtube'],
        deliveryTime: 7,
        revisions: 5,
        views: 410,
        sales: 56,
        rating: 4.8,
        reviewCount: 47,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-005',
        title: 'Animated Explainer Video',
        description: '60-second custom animated explainer video with professional voiceover and background music.',
        price: 899.00,
        discountPrice: 799.00,
        discountPercentage: 11,
        categoryId: categoryMap.get('video-animation')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800'],
        tags: ['animation', 'explainer', 'video'],
        deliveryTime: 14,
        revisions: 3,
        views: 260,
        sales: 31,
        rating: 4.9,
        reviewCount: 26,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-005',
        title: 'Stock Video Footage Bundle',
        description: '100+ high-resolution stock video clips for commercial use. 4K quality with various themes.',
        price: 79.00,
        discountPrice: 59.00,
        discountPercentage: 25,
        categoryId: categoryMap.get('video-animation')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800'],
        tags: ['stock', 'footage', '4k'],
        deliveryTime: 1,
        revisions: 0,
        views: 180,
        sales: 42,
        rating: 4.5,
        reviewCount: 19,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-006',
        title: 'Brand Identity Package',
        description: 'Complete brand identity including logo, color palette, typography, and brand guidelines document.',
        price: 799.00,
        discountPrice: 699.00,
        discountPercentage: 12,
        categoryId: categoryMap.get('graphic-design')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800'],
        tags: ['branding', 'identity', 'logo'],
        deliveryTime: 10,
        revisions: 8,
        views: 510,
        sales: 88,
        rating: 4.9,
        reviewCount: 74,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-006',
        title: '3D Product Visualization',
        description: 'Photorealistic 3D product renders for e-commerce, marketing, and presentations.',
        price: 349.00,
        discountPrice: 299.00,
        discountPercentage: 14,
        categoryId: categoryMap.get('graphic-design')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800'],
        tags: ['3d', 'rendering', 'product'],
        deliveryTime: 7,
        revisions: 4,
        views: 290,
        sales: 53,
        rating: 4.7,
        reviewCount: 39,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-007',
        title: 'Cloud VPS Hosting - 1 Year',
        description: 'High-performance cloud VPS with SSD storage, 4GB RAM, and 24/7 support.',
        price: 480.00,
        discountPrice: 420.00,
        discountPercentage: 12,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800'],
        tags: ['hosting', 'vps', 'cloud'],
        deliveryTime: 1,
        revisions: 0,
        views: 760,
        sales: 210,
        rating: 4.8,
        reviewCount: 134,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-007',
        title: 'Domain Registration Bundle',
        description: 'Register 5 premium domains with free WHOIS privacy and DNS management.',
        price: 129.00,
        discountPrice: 99.00,
        discountPercentage: 23,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800'],
        tags: ['domain', 'dns', 'web'],
        deliveryTime: 1,
        revisions: 0,
        views: 430,
        sales: 167,
        rating: 4.6,
        reviewCount: 88,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-008',
        title: 'SEO Blog Articles - 10 Pack',
        description: '10 high-quality SEO-optimized blog articles tailored to your niche and keywords.',
        price: 450.00,
        discountPrice: 399.00,
        discountPercentage: 11,
        categoryId: categoryMap.get('writing-translation')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800'],
        tags: ['writing', 'seo', 'blog'],
        deliveryTime: 14,
        revisions: 3,
        views: 390,
        sales: 72,
        rating: 4.8,
        reviewCount: 61,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-008',
        title: 'English to Spanish Translation',
        description: 'Professional translation of documents, websites, or apps. Native-level quality guaranteed.',
        price: 180.00,
        discountPrice: 149.00,
        discountPercentage: 17,
        categoryId: categoryMap.get('writing-translation')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1457369804613-52c61a468b7e?w=800'],
        tags: ['translation', 'spanish', 'english'],
        deliveryTime: 5,
        revisions: 2,
        views: 210,
        sales: 45,
        rating: 4.7,
        reviewCount: 33,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-009',
        title: 'Level 100 Gaming Account',
        description: 'Max-level gaming account with rare skins and full unlocks. Instant delivery.',
        price: 249.00,
        discountPrice: 199.00,
        discountPercentage: 20,
        categoryId: categoryMap.get('accounts')?.toString() || '',
        type: 'account',
        images: ['https://images.unsplash.com/photo-1511512578045-d9209520d8b4?w=800'],
        tags: ['gaming', 'account', 'leveled'],
        deliveryTime: 1,
        revisions: 0,
        views: 1200,
        sales: 340,
        rating: 4.4,
        reviewCount: 210,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-009',
        title: 'Social Media Account Bundle',
        description: '10 aged social media accounts with verified badges and real followers.',
        price: 499.00,
        discountPrice: 399.00,
        discountPercentage: 20,
        categoryId: categoryMap.get('accounts')?.toString() || '',
        type: 'account',
        images: ['https://images.unsplash.com/photo-1563986768609-322da13575f2?w=800'],
        tags: ['social', 'accounts', 'aged'],
        deliveryTime: 2,
        revisions: 0,
        views: 890,
        sales: 195,
        rating: 4.3,
        reviewCount: 142,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-010',
        title: 'iPhone 15 Pro Max 256GB',
        description: 'Brand new iPhone 15 Pro Max with 256GB storage. Unlocked for all carriers.',
        price: 1199.00,
        discountPrice: 1099.00,
        discountPercentage: 8,
        categoryId: categoryMap.get('electronics')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1696446701796-da75a4c0e4e4?w=800'],
        tags: ['iphone', 'apple', 'smartphone'],
        deliveryTime: 3,
        revisions: 0,
        views: 3400,
        sales: 520,
        rating: 4.9,
        reviewCount: 389,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-010',
        title: 'Sony WH-1000XM5 Headphones',
        description: 'Industry-leading noise canceling wireless headphones with 30-hour battery life.',
        price: 349.00,
        discountPrice: 299.00,
        discountPercentage: 14,
        categoryId: categoryMap.get('electronics')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800'],
        tags: ['headphones', 'sony', 'wireless'],
        deliveryTime: 2,
        revisions: 0,
        views: 2100,
        sales: 430,
        rating: 4.8,
        reviewCount: 298,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-011',
        title: 'Custom Podcast Intro Music',
        description: 'Unique 30-second podcast intro with voiceover-ready mix and full master rights.',
        price: 199.00,
        discountPrice: 149.00,
        discountPercentage: 25,
        categoryId: categoryMap.get('music-audio')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800'],
        tags: ['podcast', 'music', 'intro'],
        deliveryTime: 5,
        revisions: 3,
        views: 180,
        sales: 29,
        rating: 4.9,
        reviewCount: 22,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-011',
        title: 'Stock Music Pack - 50 Tracks',
        description: 'Versatile royalty-free music pack for videos, ads, and presentations. WAV and MP3 included.',
        price: 129.00,
        discountPrice: 99.00,
        discountPercentage: 23,
        categoryId: categoryMap.get('music-audio')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1507838153414-b4b713388a76?w=800'],
        tags: ['stock', 'music', 'royalty-free'],
        deliveryTime: 1,
        revisions: 0,
        views: 320,
        sales: 91,
        rating: 4.6,
        reviewCount: 57,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-012',
        title: 'Drone Photography Package',
        description: 'Professional aerial photos and 4K video for real estate, events, or travel content.',
        price: 599.00,
        discountPrice: 499.00,
        discountPercentage: 17,
        categoryId: categoryMap.get('photography')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800'],
        tags: ['drone', 'aerial', 'video'],
        deliveryTime: 7,
        revisions: 2,
        views: 260,
        sales: 41,
        rating: 4.8,
        reviewCount: 30,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-012',
        title: 'Premium Stock Photo Bundle',
        description: '200 high-resolution royalty-free photos for commercial use. Multiple themes included.',
        price: 89.00,
        discountPrice: 69.00,
        discountPercentage: 22,
        categoryId: categoryMap.get('photography')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800'],
        tags: ['stock', 'photos', 'royalty-free'],
        deliveryTime: 1,
        revisions: 0,
        views: 450,
        sales: 132,
        rating: 4.5,
        reviewCount: 79,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-013',
        title: 'Instagram 100K Followers Account',
        description: 'Established Instagram account with 100K+ followers in the lifestyle niche.',
        price: 3500.00,
        discountPrice: 2999.00,
        discountPercentage: 14,
        categoryId: categoryMap.get('accounts')?.toString() || '',
        type: 'account',
        images: ['https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800'],
        tags: ['instagram', 'followers', 'social'],
        deliveryTime: 1,
        revisions: 0,
        views: 5600,
        sales: 78,
        rating: 4.2,
        reviewCount: 56,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-013',
        title: 'Netflix Premium Account - 1 Year',
        description: 'Netflix Premium subscription account valid for 1 year. 4K streaming supported.',
        price: 89.00,
        discountPrice: 69.00,
        discountPercentage: 22,
        categoryId: categoryMap.get('accounts')?.toString() || '',
        type: 'account',
        images: ['https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800'],
        tags: ['netflix', 'streaming', 'account'],
        deliveryTime: 1,
        revisions: 0,
        views: 4300,
        sales: 890,
        rating: 4.1,
        reviewCount: 620,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-014',
        title: 'Adobe Photoshop Lifetime License',
        description: 'Genuine Adobe Photoshop license with lifetime validity and free updates.',
        price: 249.00,
        discountPrice: 199.00,
        discountPercentage: 20,
        categoryId: categoryMap.get('software')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800'],
        tags: ['adobe', 'photoshop', 'license'],
        deliveryTime: 1,
        revisions: 0,
        views: 1800,
        sales: 420,
        rating: 4.7,
        reviewCount: 289,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-014',
        title: 'Office 365 Business Premium',
        description: 'Office 365 Business Premium license for 5 users. Includes Teams, SharePoint, and 1TB storage.',
        price: 199.00,
        discountPrice: 149.00,
        discountPercentage: 25,
        categoryId: categoryMap.get('software')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1555066931-436663dc9c2a?w=800'],
        tags: ['office', 'microsoft', 'license'],
        deliveryTime: 1,
        revisions: 0,
        views: 1200,
        sales: 310,
        rating: 4.6,
        reviewCount: 201,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-015',
        title: 'Local SEO Package',
        description: 'Complete local SEO optimization including Google Business Profile, citations, and reviews.',
        price: 699.00,
        discountPrice: 599.00,
        discountPercentage: 14,
        categoryId: categoryMap.get('digital-marketing')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800'],
        tags: ['local-seo', 'google', 'business'],
        deliveryTime: 30,
        revisions: 5,
        views: 410,
        sales: 64,
        rating: 4.8,
        reviewCount: 52,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-015',
        title: 'Google Ads Management - 1 Month',
        description: 'Full-service Google Ads management with campaign setup, optimization, and weekly reports.',
        price: 899.00,
        discountPrice: 799.00,
        discountPercentage: 11,
        categoryId: categoryMap.get('digital-marketing')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1552664730-d307ca884978?w=800'],
        tags: ['google-ads', 'ppc', 'marketing'],
        deliveryTime: 30,
        revisions: 4,
        views: 320,
        sales: 48,
        rating: 4.7,
        reviewCount: 41,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-001',
        title: 'React SaaS Starter Kit',
        description: 'Production-ready React + Next.js SaaS starter with auth, payments, and dashboard.',
        price: 499.00,
        discountPrice: 399.00,
        discountPercentage: 20,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800'],
        tags: ['react', 'saas', 'starter'],
        deliveryTime: 1,
        revisions: 0,
        views: 670,
        sales: 145,
        rating: 4.8,
        reviewCount: 102,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-002',
        title: 'T-Shirt Design Pack',
        description: '20 modern T-shirt designs in vector format. Perfect for print-on-demand stores.',
        price: 59.00,
        discountPrice: 39.00,
        discountPercentage: 34,
        categoryId: categoryMap.get('graphic-design')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
        tags: ['t-shirt', 'print-on-demand', 'design'],
        deliveryTime: 1,
        revisions: 0,
        views: 540,
        sales: 189,
        rating: 4.6,
        reviewCount: 121,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-003',
        title: 'TikTok Growth Strategy',
        description: 'Complete TikTok growth guide with content calendar, hashtag strategy, and viral tactics.',
        price: 149.00,
        discountPrice: 99.00,
        discountPercentage: 34,
        categoryId: categoryMap.get('digital-marketing')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800'],
        tags: ['tiktok', 'growth', 'strategy'],
        deliveryTime: 1,
        revisions: 0,
        views: 980,
        sales: 267,
        rating: 4.5,
        reviewCount: 178,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-004',
        title: 'Flutter E-commerce App',
        description: 'Complete Flutter e-commerce app template with Firebase backend and Stripe payments.',
        price: 899.00,
        discountPrice: 749.00,
        discountPercentage: 17,
        categoryId: categoryMap.get('web-development')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800'],
        tags: ['flutter', 'ecommerce', 'mobile'],
        deliveryTime: 1,
        revisions: 0,
        views: 380,
        sales: 98,
        rating: 4.7,
        reviewCount: 67,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-005',
        title: 'YouTube Thumbnail Template Pack',
        description: '50 editable YouTube thumbnail templates for higher CTR and channel branding.',
        price: 49.00,
        discountPrice: 29.00,
        discountPercentage: 41,
        categoryId: categoryMap.get('video-animation')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800'],
        tags: ['youtube', 'thumbnail', 'template'],
        deliveryTime: 1,
        revisions: 0,
        views: 1200,
        sales: 356,
        rating: 4.4,
        reviewCount: 198,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-006',
        title: 'Mobile App UI Kit',
        description: '200+ screens for iOS and Android apps. Figma file with auto-layout and components.',
        price: 129.00,
        discountPrice: 99.00,
        discountPercentage: 23,
        categoryId: categoryMap.get('graphic-design')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800'],
        tags: ['ui-kit', 'figma', 'mobile'],
        deliveryTime: 1,
        revisions: 0,
        views: 890,
        sales: 276,
        rating: 4.7,
        reviewCount: 164,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-008',
        title: 'Website Copywriting Package',
        description: 'Professional copy for homepage, about, services, and contact pages. SEO-friendly.',
        price: 399.00,
        discountPrice: 329.00,
        discountPercentage: 18,
        categoryId: categoryMap.get('writing-translation')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1457369804613-52c61a468b7e?w=800'],
        tags: ['copywriting', 'website', 'seo'],
        deliveryTime: 7,
        revisions: 3,
        views: 270,
        sales: 58,
        rating: 4.8,
        reviewCount: 45,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-010',
        title: 'Samsung Galaxy S24 Ultra',
        description: 'Latest Samsung Galaxy S24 Ultra with S Pen, 256GB storage, and titanium frame.',
        price: 1299.00,
        discountPrice: 1199.00,
        discountPercentage: 8,
        categoryId: categoryMap.get('electronics')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800'],
        tags: ['samsung', 'galaxy', 'smartphone'],
        deliveryTime: 3,
        revisions: 0,
        views: 2800,
        sales: 410,
        rating: 4.9,
        reviewCount: 312,
        featured: true,
        status: 'active',
      },
      {
        sellerId: 'user-014',
        title: 'Antivirus Software - 3 Devices',
        description: 'Top-rated antivirus protection for up to 3 devices. 1-year subscription with real-time protection.',
        price: 49.00,
        discountPrice: 34.00,
        discountPercentage: 31,
        categoryId: categoryMap.get('software')?.toString() || '',
        type: 'goods',
        images: ['https://images.unsplash.com/photo-1555066931-436663dc9c2a?w=800'],
        tags: ['antivirus', 'security', 'software'],
        deliveryTime: 1,
        revisions: 0,
        views: 950,
        sales: 380,
        rating: 4.5,
        reviewCount: 245,
        featured: false,
        status: 'active',
      },
      {
        sellerId: 'user-012',
        title: 'Real Estate Photo Editing',
        description: 'Professional HDR editing and virtual staging for real estate listings.',
        price: 199.00,
        discountPrice: 149.00,
        discountPercentage: 25,
        categoryId: categoryMap.get('photography')?.toString() || '',
        type: 'service',
        images: ['https://images.unsplash.com/photo-1502915519262-6c5f82e8b9e5?w=800'],
        tags: ['real-estate', 'hdr', 'editing'],
        deliveryTime: 2,
        revisions: 2,
        views: 340,
        sales: 112,
        rating: 4.7,
        reviewCount: 84,
        featured: false,
        status: 'active',
      },
    ];

    await Listing.insertMany(listings);

    const allListings = await Listing.find().lean();
    const demoBuyerId = 'user-buyer-001';

    for (const listing of allListings) {
      const existingReview = await Review.findOne({ listingId: listing._id, reviewerId: demoBuyerId });
      if (!existingReview) {
        await Review.create({
          orderId: 'order-mock-001',
          reviewerId: demoBuyerId,
          revieweeId: listing.sellerId,
          listingId: listing._id,
          rating: Math.floor(Math.random() * 2) + 4,
          content: 'Great work! Highly recommended. The seller delivered exactly what was promised and the quality exceeded my expectations.',
        });
      }
    }
  }

  return {
    users: await User.countDocuments(),
    categories: await Category.countDocuments(),
    listings: await Listing.countDocuments(),
    reviews: await Review.countDocuments(),
  };
}

export async function GET(request: NextRequest) {
  try {
    const secret = request.nextUrl.searchParams.get('secret');
    if (secret !== process.env.SEED_SECRET) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const result = await seed();
    return NextResponse.json({ ok: true, result });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ ok: false, error: message }, { status: 500 });
  }
}
